services:
  db:
    image: postgres:13 # Указываем версию образа PostgreSQL
    container_name: postgres_db # Название контейнера
    environment:
      POSTGRES_USER: myuser # Имя пользователя PostgreSQL
      POSTGRES_PASSWORD: mypassword # Пароль для пользователя PostgreSQL
      POSTGRES_DB: mydatabase # Имя базы данных
    ports:
      - "5432:5432" # Проброс порта PostgreSQL
    volumes:
      - db_data:/var/lib/postgresql/data # Настройка постоянного хранилища данных

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_CFG_NODE_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka-data:/bitnami/kafka
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

volumes:
  db_data: # Определение именованного тома для данных PostgreSQL
  redis-data:
    driver: local
  kafka-data:
    driver: local
